CREATE TABLE IF NOT EXISTS `languages` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `language_code` varchar(10) NOT NULL,
  `language_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 143 DEFAULT CHARSET=utf8;


INSERT INTO `languages` (`id`, `language_code`, `language_name`) VALUES
(1, 'af', 'Afrikaans'),
(2, 'sq', 'Albanian'),
(3, 'am', 'Amharic'),
(4, 'ar', 'Arabic'),
(5, 'an', 'Aragonese'),
(6, 'hy', 'Armenian'),
(7, 'ast', 'Asturian'),
(8, 'az', 'Azerbaijani'),
(9, 'eu', 'Basque'),
(10, 'be', 'Belarusian'),
(11, 'bn', 'Bengali'),
(12, 'bs', 'Bosnian'),
(13, 'br', 'Breton'),
(14, 'bg', 'Bulgarian'),
(15, 'ca', 'Catalan'),
(16, 'ckb', 'Central Kurdish'),
(17, 'zh', 'Chinese'),
(18, 'zh-HK', 'Chinese (Hong Kong)'),
(19, 'zh-CN', 'Chinese (Simplified)'),
(20, 'zh-TW', 'Chinese (Traditional)'),
(21, 'co', 'Corsican'),
(22, 'hr', 'Croatian'),
(23, 'cs', 'Czech'),
(24, 'da', 'Danish'),
(25, 'nl', 'Dutch'),
(26, 'en', 'English'),
(27, 'en-AU', 'English (Australia)'),
(28, 'en-CA', 'English (Canada)'),
(29, 'en-IN', 'English (India)'),
(30, 'en-NZ', 'English (New Zealand)'),
(31, 'en-ZA', 'English (South Africa)'),
(32, 'en-GB', 'English (United Kingdom)'),
(33, 'en-US', 'English (United States)'),
(34, 'eo', 'Esperanto'),
(35, 'et', 'Estonian'),
(36, 'fo', 'Faroese'),
(37, 'fil', 'Filipino'),
(38, 'fi', 'Finnish'),
(39, 'fr', 'French'),
(40, 'fr-CA', 'French (Canada)'),
(41, 'fr-FR', 'French (France)'),
(42, 'fr-CH', 'French (Switzerland)'),
(43, 'gl', 'Galician'),
(44, 'ka', 'Georgian'),
(45, 'de', 'German'),
(46, 'de-AT', 'German (Austria)'),
(47, 'de-DE', 'German (Germany)'),
(48, 'de-LI', 'German (Liechtenstein)'),
(49, 'de-CH', 'German (Switzerland)'),
(50, 'el', 'Greek'),
(51, 'gn', 'Guarani'),
(52, 'gu', 'Gujarati'),
(53, 'ha', 'Hausa'),
(54, 'haw', 'Hawaiian'),
(55, 'he', 'Hebrew'),
(56, 'hi', 'Hindi'),
(57, 'hu', 'Hungarian '),
(58, 'is', 'Icelandic '),
(59, 'id', 'Indonesian'),
(60, 'ia', 'Interlingua'),
(61, 'ga', 'Irish'),
(62, 'it', 'Italian'),
(63, 'it-IT', 'Italian (Italy)'),
(64, 'it-CH', 'Italian (Switzerland)'),
(65, 'ja', 'Japanese'),
(66, 'kn', 'Kannada'),
(67, 'kk', 'Kazakh'),
(68, 'km', 'Khmer'),
(69, 'ko', 'Korean'),
(70, 'ku', 'Kurdish'),
(71, 'ky', 'Kyrgyz'),
(72, 'lo', 'Lao'),
(73, 'la', 'Latin'),
(74, 'lv', 'Latvian'),
(75, 'ln', 'Lingala'),
(76, 'lt', 'Lithuanian'),
(77, 'mk', 'Macedonian'),
(78, 'ms', 'Malay'),
(79, 'ml', 'Malayalam'),
(80, 'mt', 'Maltese'),
(81, 'mr', 'Marathi'),
(82, 'mn', 'Mongolian'),
(83, 'ne', 'Nepali'),
(84, 'no', 'Norwegian'),
(85, 'nb', 'Norwegian Bokmål'),
(86, 'nn', 'Norwegian Nynorsk'),
(87, 'oc', 'Occitan'),
(88, 'or', 'Oriya'),
(89, 'om', 'Oromo'),
(90, 'ps', 'Pashto'),
(91, 'fa', 'Persian'),
(92, 'pl', 'Polish'),
(93, 'pt', 'Portuguese'),
(94, 'pt-BR', 'Portuguese (Brazil)'),
(95, 'pt-PT', 'Portuguese (Portugal)'),
(96, 'pa', 'Punjab'),
(97, 'qu', 'Quechua'),
(98, 'ro', 'Romanian'),
(99, 'mo', 'Romanian (Moldova)'),
(100, 'rm', 'Romansh'),
(101, 'ru', 'Russian'),
(102, 'gd', 'Scottish Gaelic'),
(103, 'sr', 'Serbian'),
(104, 'sh', 'Serbo-Croatian'),
(105, 'sn', 'Shona'),
(106, 'sd', 'Sindhi'),
(107, 'si', 'Sinhala'),
(108, 'sk', 'Slovak'),
(109, 'sl', 'Slovenian'),
(110, 'so', 'Somali'),
(111, 'st', 'Southern Sotho'),
(112, 'es', 'Spanish'),
(113, 'es-AR', 'Spanish (Argentina)'),
(114, 'es-419', 'Spanish (Latin America)'),
(115, 'es-MX', 'Spanish (Mexico)'),
(116, 'es-ES', 'Spanish (Spain)'),
(117, 'es-US', 'Spanish (United States)'),
(118, 'su', 'Sundanese'),
(119, 'sw', 'Swahili'),
(120, 'sv', 'Swedish'),
(121, 'tg', 'Tajik'),
(122, 'ta', 'Tamil'),
(123, 'tt', 'Tatar'),
(124, 'te', 'Telugu'),
(125, 'th', 'Thai'),
(126, 'ti', 'Tigrinya'),
(127, 'to', 'Tongan'),
(128, 'tr', 'Turkish'),
(129, 'tk', 'Turkmen'),
(130, 'tw', 'Twi'),
(131, 'uk', 'Ukrainian'),
(132, 'ur', 'Urdu'),
(133, 'ug', 'Uyghur'),
(134, 'uz', 'Uzbek'),
(135, 'vi', 'Vietnamese'),
(136, 'wa', 'Walloon'),
(137, 'cy', 'Welsh'),
(138, 'fy', 'Western Frisian'),
(139, 'xh', 'Xhosa'),
(140, 'yi', 'Yiddish'),
(141, 'yo', 'Yoruba'),
(142, 'zu', 'Zulu');